# Generated by Django 5.2.1 on 2025-08-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('last_name', models.CharField(max_length=256, null=True, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone_or_email', models.CharField(max_length=256, verbose_name='phone or email')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
                'db_table': 'teachers',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app_common.teacher'),
        ),
    ]
